[profile.default]
src = "src"                    # Carpeta donde se encuentran los contratos fuente
out = "out"                    # Carpeta donde se generarán los artefactos compilados
libs = ["lib"]                 # Carpeta donde se encuentran las bibliotecas externas
ignore = ["src/V1.backup/**"]  # Ignorar archivos de backup
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@forge-std/=lib/forge-std/",
    "@polytope-labs/ismp-solidity/=lib/hyperbridge/evm/node_modules/@polytope-labs/ismp-solidity/"
]

# Opciones de optimización
optimizer = true
optimizer_runs = 200
via_ir = true

# Permisos de acceso a archivos
fs_permissions = [
    { access = "read", path = "./" },
    { access = "write", path = "./" }
]